package logger

const (
	Subject  = "subject"
	IP       = "ip"
	Exchange = "exchange"
	Queue    = "queue"
	Cmd      = "cmd"
	Data     = "data"
	Days     = "days"
	Code     = "code"
	Target   = "target"
	Outdated = "outdated"
	Targets  = "targets"
	CertID   = "cert_id"
	Reason   = "reason"
	Level    = "level"
	Name     = "name"
	Port     = "port"
	Action   = "action"
	Count    = "count"
	Hours    = "hours"
	Minutes  = "minutes"
	Serial   = "remote_serial"
	DbSerial = "db_serial"
	Service  = "service"
	Reply    = "reply"

	Requeue   = "requeue"
	Rejected  = "rejected"
	Ack       = "acknowledged"
	Published = "published"
	Received  = "received"
	Success   = "success"
	Skip      = "skipping"
	Get       = "get"
	Consumed  = "consumed"
	Revoked   = "revoked"
	Unknown   = "unknown"
	Enroll    = "enroll"
	Ok        = "ok"
	Added     = "added"
	Ready     = "ready"
)
