// Code generated by protoc-gen-go. DO NOT EDIT.
// source: londopb/londo.proto

package londopb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Subject struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Certificate          string   `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`
	PrivateKey           string   `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	AltNames             []string `protobuf:"bytes,4,rep,name=alt_names,json=altNames,proto3" json:"alt_names,omitempty"`
	Targets              []string `protobuf:"bytes,5,rep,name=targets,proto3" json:"targets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subject) Reset()         { *m = Subject{} }
func (m *Subject) String() string { return proto.CompactTextString(m) }
func (*Subject) ProtoMessage()    {}
func (*Subject) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d42104e625ed99, []int{0}
}

func (m *Subject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subject.Unmarshal(m, b)
}
func (m *Subject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subject.Marshal(b, m, deterministic)
}
func (m *Subject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subject.Merge(m, src)
}
func (m *Subject) XXX_Size() int {
	return xxx_messageInfo_Subject.Size(m)
}
func (m *Subject) XXX_DiscardUnknown() {
	xxx_messageInfo_Subject.DiscardUnknown(m)
}

var xxx_messageInfo_Subject proto.InternalMessageInfo

func (m *Subject) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Subject) GetCertificate() string {
	if m != nil {
		return m.Certificate
	}
	return ""
}

func (m *Subject) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *Subject) GetAltNames() []string {
	if m != nil {
		return m.AltNames
	}
	return nil
}

func (m *Subject) GetTargets() []string {
	if m != nil {
		return m.Targets
	}
	return nil
}

type GetSubjectRequest struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSubjectRequest) Reset()         { *m = GetSubjectRequest{} }
func (m *GetSubjectRequest) String() string { return proto.CompactTextString(m) }
func (*GetSubjectRequest) ProtoMessage()    {}
func (*GetSubjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d42104e625ed99, []int{1}
}

func (m *GetSubjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSubjectRequest.Unmarshal(m, b)
}
func (m *GetSubjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSubjectRequest.Marshal(b, m, deterministic)
}
func (m *GetSubjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSubjectRequest.Merge(m, src)
}
func (m *GetSubjectRequest) XXX_Size() int {
	return xxx_messageInfo_GetSubjectRequest.Size(m)
}
func (m *GetSubjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSubjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSubjectRequest proto.InternalMessageInfo

func (m *GetSubjectRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

type TargetRequest struct {
	Target               []string `protobuf:"bytes,1,rep,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TargetRequest) Reset()         { *m = TargetRequest{} }
func (m *TargetRequest) String() string { return proto.CompactTextString(m) }
func (*TargetRequest) ProtoMessage()    {}
func (*TargetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d42104e625ed99, []int{2}
}

func (m *TargetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TargetRequest.Unmarshal(m, b)
}
func (m *TargetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TargetRequest.Marshal(b, m, deterministic)
}
func (m *TargetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TargetRequest.Merge(m, src)
}
func (m *TargetRequest) XXX_Size() int {
	return xxx_messageInfo_TargetRequest.Size(m)
}
func (m *TargetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TargetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TargetRequest proto.InternalMessageInfo

func (m *TargetRequest) GetTarget() []string {
	if m != nil {
		return m.Target
	}
	return nil
}

type ForTargetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForTargetRequest) Reset()         { *m = ForTargetRequest{} }
func (m *ForTargetRequest) String() string { return proto.CompactTextString(m) }
func (*ForTargetRequest) ProtoMessage()    {}
func (*ForTargetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d42104e625ed99, []int{3}
}

func (m *ForTargetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForTargetRequest.Unmarshal(m, b)
}
func (m *ForTargetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForTargetRequest.Marshal(b, m, deterministic)
}
func (m *ForTargetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForTargetRequest.Merge(m, src)
}
func (m *ForTargetRequest) XXX_Size() int {
	return xxx_messageInfo_ForTargetRequest.Size(m)
}
func (m *ForTargetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForTargetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForTargetRequest proto.InternalMessageInfo

type GetSubjectResponse struct {
	Subject              *Subject `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSubjectResponse) Reset()         { *m = GetSubjectResponse{} }
func (m *GetSubjectResponse) String() string { return proto.CompactTextString(m) }
func (*GetSubjectResponse) ProtoMessage()    {}
func (*GetSubjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d42104e625ed99, []int{4}
}

func (m *GetSubjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSubjectResponse.Unmarshal(m, b)
}
func (m *GetSubjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSubjectResponse.Marshal(b, m, deterministic)
}
func (m *GetSubjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSubjectResponse.Merge(m, src)
}
func (m *GetSubjectResponse) XXX_Size() int {
	return xxx_messageInfo_GetSubjectResponse.Size(m)
}
func (m *GetSubjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSubjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSubjectResponse proto.InternalMessageInfo

func (m *GetSubjectResponse) GetSubject() *Subject {
	if m != nil {
		return m.Subject
	}
	return nil
}

// New Subject
type NewSubject struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	AltNames             []string `protobuf:"bytes,2,rep,name=alt_names,json=altNames,proto3" json:"alt_names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewSubject) Reset()         { *m = NewSubject{} }
func (m *NewSubject) String() string { return proto.CompactTextString(m) }
func (*NewSubject) ProtoMessage()    {}
func (*NewSubject) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d42104e625ed99, []int{5}
}

func (m *NewSubject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewSubject.Unmarshal(m, b)
}
func (m *NewSubject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewSubject.Marshal(b, m, deterministic)
}
func (m *NewSubject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewSubject.Merge(m, src)
}
func (m *NewSubject) XXX_Size() int {
	return xxx_messageInfo_NewSubject.Size(m)
}
func (m *NewSubject) XXX_DiscardUnknown() {
	xxx_messageInfo_NewSubject.DiscardUnknown(m)
}

var xxx_messageInfo_NewSubject proto.InternalMessageInfo

func (m *NewSubject) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *NewSubject) GetAltNames() []string {
	if m != nil {
		return m.AltNames
	}
	return nil
}

type AddNewSubjectRequest struct {
	Subject              *NewSubject `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddNewSubjectRequest) Reset()         { *m = AddNewSubjectRequest{} }
func (m *AddNewSubjectRequest) String() string { return proto.CompactTextString(m) }
func (*AddNewSubjectRequest) ProtoMessage()    {}
func (*AddNewSubjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d42104e625ed99, []int{6}
}

func (m *AddNewSubjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNewSubjectRequest.Unmarshal(m, b)
}
func (m *AddNewSubjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNewSubjectRequest.Marshal(b, m, deterministic)
}
func (m *AddNewSubjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNewSubjectRequest.Merge(m, src)
}
func (m *AddNewSubjectRequest) XXX_Size() int {
	return xxx_messageInfo_AddNewSubjectRequest.Size(m)
}
func (m *AddNewSubjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNewSubjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddNewSubjectRequest proto.InternalMessageInfo

func (m *AddNewSubjectRequest) GetSubject() *NewSubject {
	if m != nil {
		return m.Subject
	}
	return nil
}

// New Token
type JWTToken struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JWTToken) Reset()         { *m = JWTToken{} }
func (m *JWTToken) String() string { return proto.CompactTextString(m) }
func (*JWTToken) ProtoMessage()    {}
func (*JWTToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d42104e625ed99, []int{7}
}

func (m *JWTToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JWTToken.Unmarshal(m, b)
}
func (m *JWTToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JWTToken.Marshal(b, m, deterministic)
}
func (m *JWTToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JWTToken.Merge(m, src)
}
func (m *JWTToken) XXX_Size() int {
	return xxx_messageInfo_JWTToken.Size(m)
}
func (m *JWTToken) XXX_DiscardUnknown() {
	xxx_messageInfo_JWTToken.DiscardUnknown(m)
}

var xxx_messageInfo_JWTToken proto.InternalMessageInfo

func (m *JWTToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetTokenRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenRequest) Reset()         { *m = GetTokenRequest{} }
func (m *GetTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetTokenRequest) ProtoMessage()    {}
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d42104e625ed99, []int{8}
}

func (m *GetTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenRequest.Unmarshal(m, b)
}
func (m *GetTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenRequest.Merge(m, src)
}
func (m *GetTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetTokenRequest.Size(m)
}
func (m *GetTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenRequest proto.InternalMessageInfo

type GetTokenResponse struct {
	Token                *JWTToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetTokenResponse) Reset()         { *m = GetTokenResponse{} }
func (m *GetTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetTokenResponse) ProtoMessage()    {}
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d42104e625ed99, []int{9}
}

func (m *GetTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenResponse.Unmarshal(m, b)
}
func (m *GetTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenResponse.Merge(m, src)
}
func (m *GetTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetTokenResponse.Size(m)
}
func (m *GetTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenResponse proto.InternalMessageInfo

func (m *GetTokenResponse) GetToken() *JWTToken {
	if m != nil {
		return m.Token
	}
	return nil
}

func init() {
	proto.RegisterType((*Subject)(nil), "londoapi.v1.Subject")
	proto.RegisterType((*GetSubjectRequest)(nil), "londoapi.v1.GetSubjectRequest")
	proto.RegisterType((*TargetRequest)(nil), "londoapi.v1.TargetRequest")
	proto.RegisterType((*ForTargetRequest)(nil), "londoapi.v1.ForTargetRequest")
	proto.RegisterType((*GetSubjectResponse)(nil), "londoapi.v1.GetSubjectResponse")
	proto.RegisterType((*NewSubject)(nil), "londoapi.v1.NewSubject")
	proto.RegisterType((*AddNewSubjectRequest)(nil), "londoapi.v1.AddNewSubjectRequest")
	proto.RegisterType((*JWTToken)(nil), "londoapi.v1.JWTToken")
	proto.RegisterType((*GetTokenRequest)(nil), "londoapi.v1.GetTokenRequest")
	proto.RegisterType((*GetTokenResponse)(nil), "londoapi.v1.GetTokenResponse")
}

func init() { proto.RegisterFile("londopb/londo.proto", fileDescriptor_f3d42104e625ed99) }

var fileDescriptor_f3d42104e625ed99 = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0xce, 0xd2, 0x40,
	0x10, 0x4d, 0x3f, 0xe4, 0xa7, 0xd3, 0x10, 0x61, 0x40, 0x6d, 0x50, 0xa4, 0xf6, 0x46, 0x12, 0x63,
	0x15, 0x7c, 0x00, 0x23, 0x18, 0x89, 0x1a, 0xb9, 0x80, 0x26, 0x24, 0xde, 0x90, 0x52, 0x46, 0x53,
	0xc1, 0xb6, 0xb6, 0x0b, 0x86, 0x87, 0xf1, 0x01, 0x7c, 0x4b, 0xc3, 0x76, 0x97, 0x76, 0x51, 0xe4,
	0xbb, 0xea, 0xce, 0xdf, 0x99, 0xd3, 0x73, 0x36, 0x0b, 0xad, 0x6d, 0x14, 0xae, 0xa3, 0x78, 0xf5,
	0x82, 0x7f, 0x9d, 0x38, 0x89, 0x58, 0x84, 0x06, 0x0f, 0xbc, 0x38, 0x70, 0xf6, 0x03, 0xfb, 0x97,
	0x06, 0xd5, 0xf9, 0x6e, 0xf5, 0x8d, 0x7c, 0x86, 0x26, 0x54, 0xd3, 0xec, 0x68, 0x6a, 0x96, 0xd6,
	0xd7, 0x67, 0x32, 0x44, 0x0b, 0x0c, 0x9f, 0x12, 0x16, 0x7c, 0x09, 0x7c, 0x8f, 0x91, 0x79, 0xc3,
	0xab, 0xc5, 0x14, 0xf6, 0xc0, 0x88, 0x93, 0x60, 0xef, 0x31, 0x5a, 0x6e, 0xe8, 0x60, 0x96, 0x78,
	0x07, 0x88, 0xd4, 0x47, 0x3a, 0xe0, 0x43, 0xd0, 0xbd, 0x2d, 0x5b, 0x86, 0xde, 0x77, 0x4a, 0xcd,
	0x3b, 0x56, 0xa9, 0xaf, 0xcf, 0x6a, 0xde, 0x96, 0x4d, 0x8f, 0xf1, 0x71, 0x33, 0xf3, 0x92, 0xaf,
	0xc4, 0x52, 0xb3, 0xcc, 0x4b, 0x32, 0xb4, 0x9f, 0x43, 0x73, 0x42, 0x4c, 0x30, 0x9c, 0xd1, 0x8f,
	0x1d, 0xa5, 0xff, 0x21, 0x6a, 0x3f, 0x85, 0xba, 0xcb, 0x27, 0x65, 0xeb, 0x7d, 0xa8, 0x64, 0x50,
	0xa6, 0xc6, 0x81, 0x45, 0x64, 0x23, 0x34, 0xde, 0x45, 0x89, 0xd2, 0x6b, 0xbf, 0x05, 0x2c, 0xee,
	0x4a, 0xe3, 0x28, 0x4c, 0x09, 0x1d, 0x75, 0x99, 0x31, 0x6c, 0x3b, 0x05, 0x01, 0x1d, 0xd9, 0x7e,
	0xa2, 0x30, 0x06, 0x98, 0xd2, 0xcf, 0xeb, 0x9a, 0x2a, 0x82, 0xdc, 0xa8, 0x82, 0xd8, 0xef, 0xa1,
	0xfd, 0x66, 0xbd, 0xce, 0x71, 0xe4, 0xef, 0x0c, 0xce, 0xc9, 0x3c, 0x50, 0xc8, 0x14, 0x06, 0x4e,
	0x7c, 0x2c, 0xa8, 0x7d, 0x58, 0xb8, 0x6e, 0xb4, 0xa1, 0x10, 0xdb, 0x50, 0x66, 0xc7, 0x83, 0xe0,
	0x92, 0x05, 0x76, 0x13, 0xee, 0x4e, 0x88, 0xf1, 0x0e, 0x29, 0xc5, 0x6b, 0x68, 0xe4, 0x29, 0x21,
	0xc4, 0xb3, 0xe2, 0xb0, 0x31, 0xbc, 0xa7, 0x6c, 0x96, 0x2b, 0x04, 0xe6, 0xf0, 0x77, 0x09, 0x8c,
	0x31, 0x25, 0x6c, 0x4e, 0xc9, 0x3e, 0xf0, 0x09, 0x3f, 0x01, 0xe4, 0xda, 0xe2, 0x63, 0x65, 0xf6,
	0x2f, 0x83, 0x3b, 0xbd, 0x8b, 0x75, 0xc1, 0xc5, 0x85, 0x56, 0x9e, 0x4d, 0x47, 0x87, 0xcc, 0x48,
	0xec, 0x28, 0x73, 0x8a, 0xbb, 0x57, 0x31, 0x5f, 0x6a, 0xb8, 0x28, 0xa2, 0x9e, 0xae, 0x07, 0x76,
	0x95, 0xc9, 0xf3, 0x6b, 0x73, 0x1b, 0xe0, 0x39, 0xd4, 0x15, 0x3b, 0xf1, 0x89, 0x32, 0xf3, 0x2f,
	0xab, 0xaf, 0x6b, 0x30, 0x81, 0x9a, 0xf4, 0x08, 0x1f, 0x9d, 0x37, 0x17, 0xdd, 0xec, 0x74, 0x2f,
	0x54, 0x33, 0xa0, 0x91, 0xfe, 0xb9, 0x2a, 0xde, 0x89, 0x55, 0x85, 0x3f, 0x11, 0xaf, 0xfe, 0x04,
	0x00, 0x00, 0xff, 0xff, 0xfc, 0x3c, 0xfd, 0x1d, 0x39, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CertServiceClient is the client API for CertService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CertServiceClient interface {
	GetSubject(ctx context.Context, in *GetSubjectRequest, opts ...grpc.CallOption) (*GetSubjectResponse, error)
	GetSubjectsByTarget(ctx context.Context, in *TargetRequest, opts ...grpc.CallOption) (CertService_GetSubjectsByTargetClient, error)
	// Response is determined by requester's IP address
	GetSubjectForTarget(ctx context.Context, in *ForTargetRequest, opts ...grpc.CallOption) (CertService_GetSubjectForTargetClient, error)
	// Not implemented
	AddNewSubject(ctx context.Context, in *AddNewSubjectRequest, opts ...grpc.CallOption) (*GetSubjectResponse, error)
	GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error)
}

type certServiceClient struct {
	cc *grpc.ClientConn
}

func NewCertServiceClient(cc *grpc.ClientConn) CertServiceClient {
	return &certServiceClient{cc}
}

func (c *certServiceClient) GetSubject(ctx context.Context, in *GetSubjectRequest, opts ...grpc.CallOption) (*GetSubjectResponse, error) {
	out := new(GetSubjectResponse)
	err := c.cc.Invoke(ctx, "/londoapi.v1.CertService/GetSubject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certServiceClient) GetSubjectsByTarget(ctx context.Context, in *TargetRequest, opts ...grpc.CallOption) (CertService_GetSubjectsByTargetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CertService_serviceDesc.Streams[0], "/londoapi.v1.CertService/GetSubjectsByTarget", opts...)
	if err != nil {
		return nil, err
	}
	x := &certServiceGetSubjectsByTargetClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CertService_GetSubjectsByTargetClient interface {
	Recv() (*GetSubjectResponse, error)
	grpc.ClientStream
}

type certServiceGetSubjectsByTargetClient struct {
	grpc.ClientStream
}

func (x *certServiceGetSubjectsByTargetClient) Recv() (*GetSubjectResponse, error) {
	m := new(GetSubjectResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *certServiceClient) GetSubjectForTarget(ctx context.Context, in *ForTargetRequest, opts ...grpc.CallOption) (CertService_GetSubjectForTargetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CertService_serviceDesc.Streams[1], "/londoapi.v1.CertService/GetSubjectForTarget", opts...)
	if err != nil {
		return nil, err
	}
	x := &certServiceGetSubjectForTargetClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CertService_GetSubjectForTargetClient interface {
	Recv() (*GetSubjectResponse, error)
	grpc.ClientStream
}

type certServiceGetSubjectForTargetClient struct {
	grpc.ClientStream
}

func (x *certServiceGetSubjectForTargetClient) Recv() (*GetSubjectResponse, error) {
	m := new(GetSubjectResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *certServiceClient) AddNewSubject(ctx context.Context, in *AddNewSubjectRequest, opts ...grpc.CallOption) (*GetSubjectResponse, error) {
	out := new(GetSubjectResponse)
	err := c.cc.Invoke(ctx, "/londoapi.v1.CertService/AddNewSubject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certServiceClient) GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error) {
	out := new(GetTokenResponse)
	err := c.cc.Invoke(ctx, "/londoapi.v1.CertService/GetToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CertServiceServer is the server API for CertService service.
type CertServiceServer interface {
	GetSubject(context.Context, *GetSubjectRequest) (*GetSubjectResponse, error)
	GetSubjectsByTarget(*TargetRequest, CertService_GetSubjectsByTargetServer) error
	// Response is determined by requester's IP address
	GetSubjectForTarget(*ForTargetRequest, CertService_GetSubjectForTargetServer) error
	// Not implemented
	AddNewSubject(context.Context, *AddNewSubjectRequest) (*GetSubjectResponse, error)
	GetToken(context.Context, *GetTokenRequest) (*GetTokenResponse, error)
}

func RegisterCertServiceServer(s *grpc.Server, srv CertServiceServer) {
	s.RegisterService(&_CertService_serviceDesc, srv)
}

func _CertService_GetSubject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertServiceServer).GetSubject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/londoapi.v1.CertService/GetSubject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertServiceServer).GetSubject(ctx, req.(*GetSubjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertService_GetSubjectsByTarget_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TargetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CertServiceServer).GetSubjectsByTarget(m, &certServiceGetSubjectsByTargetServer{stream})
}

type CertService_GetSubjectsByTargetServer interface {
	Send(*GetSubjectResponse) error
	grpc.ServerStream
}

type certServiceGetSubjectsByTargetServer struct {
	grpc.ServerStream
}

func (x *certServiceGetSubjectsByTargetServer) Send(m *GetSubjectResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CertService_GetSubjectForTarget_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ForTargetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CertServiceServer).GetSubjectForTarget(m, &certServiceGetSubjectForTargetServer{stream})
}

type CertService_GetSubjectForTargetServer interface {
	Send(*GetSubjectResponse) error
	grpc.ServerStream
}

type certServiceGetSubjectForTargetServer struct {
	grpc.ServerStream
}

func (x *certServiceGetSubjectForTargetServer) Send(m *GetSubjectResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CertService_AddNewSubject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNewSubjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertServiceServer).AddNewSubject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/londoapi.v1.CertService/AddNewSubject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertServiceServer).AddNewSubject(ctx, req.(*AddNewSubjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertService_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertServiceServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/londoapi.v1.CertService/GetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertServiceServer).GetToken(ctx, req.(*GetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CertService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "londoapi.v1.CertService",
	HandlerType: (*CertServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSubject",
			Handler:    _CertService_GetSubject_Handler,
		},
		{
			MethodName: "AddNewSubject",
			Handler:    _CertService_AddNewSubject_Handler,
		},
		{
			MethodName: "GetToken",
			Handler:    _CertService_GetToken_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSubjectsByTarget",
			Handler:       _CertService_GetSubjectsByTarget_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetSubjectForTarget",
			Handler:       _CertService_GetSubjectForTarget_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "londopb/londo.proto",
}
